<?php

namespace Container1s8FPXX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RdBZ6dkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rdBZ6dk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rdBZ6dk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'repo' => ['privates', 'App\\Repository\\LivraisonRepository', 'getLivraisonRepositoryService', true],
        ], [
            'doctrine' => '?',
            'repo' => 'App\\Repository\\LivraisonRepository',
        ]);
    }
}
