security:
    enable_authenticator_manager: true

    # Hachage des mots de passe
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Configuration des providers
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            form_login:
                default_target_path: /default_target                                                                           
                login_path: app_login
                check_path: app_login
                username_parameter: username   # <--- Ajouté
                password_parameter: password   # <--- Ajouté
                  # Redirection après connexion réussie
            logout:
                path: app_logout
                target: app_login

    # Contrôle d'accès
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/agriculture, roles: ROLE_AGRICULTURE }
        - { path: ^/veterinaire, roles: ROLE_VETERINAIRE }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
