<?php

namespace ContainerYp6jxb7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PJaOpm3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PJaOpm3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.PJaOpm3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\CommandeController::Add' => ['privates', '.service_locator.ESajd_W', 'get_ServiceLocator_ESajdWService', true],
            'App\\Controller\\CommandeController::AfficheCommande' => ['privates', '.service_locator.NtdryJq', 'get_ServiceLocator_NtdryJqService', true],
            'App\\Controller\\CommandeController::AfficheCommandeAdmin' => ['privates', '.service_locator.NtdryJq', 'get_ServiceLocator_NtdryJqService', true],
            'App\\Controller\\CommandeController::Delete' => ['privates', '.service_locator.wtsfFeq', 'get_ServiceLocator_WtsfFeqService', true],
            'App\\Controller\\CommandeController::sendMessage' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\CommandeController::update' => ['privates', '.service_locator.Ist8Mf6', 'get_ServiceLocator_Ist8Mf6Service', true],
            'App\\Controller\\ConseilController::add' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\ConseilController::delete' => ['privates', '.service_locator.YSLHiAd', 'get_ServiceLocator_YSLHiAdService', true],
            'App\\Controller\\ConseilController::index' => ['privates', '.service_locator.2p4g_J6', 'get_ServiceLocator_2p4gJ6Service', true],
            'App\\Controller\\ConseilController::update' => ['privates', '.service_locator.YSLHiAd', 'get_ServiceLocator_YSLHiAdService', true],
            'App\\Controller\\DemandeController::add' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\DemandeController::conseiller' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\DemandeController::delete' => ['privates', '.service_locator.jJfxXMU', 'get_ServiceLocator_JJfxXMUService', true],
            'App\\Controller\\DemandeController::index' => ['privates', '.service_locator.KKOSzu8', 'get_ServiceLocator_KKOSzu8Service', true],
            'App\\Controller\\DemandeController::indexAdmin' => ['privates', '.service_locator.KKOSzu8', 'get_ServiceLocator_KKOSzu8Service', true],
            'App\\Controller\\DemandeController::update' => ['privates', '.service_locator.jJfxXMU', 'get_ServiceLocator_JJfxXMUService', true],
            'App\\Controller\\LivraisonController::Add' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\LivraisonController::AfficheLivraison' => ['privates', '.service_locator.7EutsTK', 'get_ServiceLocator_7EutsTKService', true],
            'App\\Controller\\LivraisonController::AfficheLivraison1' => ['privates', '.service_locator.RPKG70Q', 'get_ServiceLocator_RPKG70QService', true],
            'App\\Controller\\LivraisonController::Delete' => ['privates', '.service_locator.kXoQeZ1', 'get_ServiceLocator_KXoQeZ1Service', true],
            'App\\Controller\\LivraisonController::update' => ['privates', '.service_locator.rdBZ6dk', 'get_ServiceLocator_RdBZ6dkService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\CommandeController:Add' => ['privates', '.service_locator.ESajd_W', 'get_ServiceLocator_ESajdWService', true],
            'App\\Controller\\CommandeController:AfficheCommande' => ['privates', '.service_locator.NtdryJq', 'get_ServiceLocator_NtdryJqService', true],
            'App\\Controller\\CommandeController:AfficheCommandeAdmin' => ['privates', '.service_locator.NtdryJq', 'get_ServiceLocator_NtdryJqService', true],
            'App\\Controller\\CommandeController:Delete' => ['privates', '.service_locator.wtsfFeq', 'get_ServiceLocator_WtsfFeqService', true],
            'App\\Controller\\CommandeController:sendMessage' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\CommandeController:update' => ['privates', '.service_locator.Ist8Mf6', 'get_ServiceLocator_Ist8Mf6Service', true],
            'App\\Controller\\ConseilController:add' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\ConseilController:delete' => ['privates', '.service_locator.YSLHiAd', 'get_ServiceLocator_YSLHiAdService', true],
            'App\\Controller\\ConseilController:index' => ['privates', '.service_locator.2p4g_J6', 'get_ServiceLocator_2p4gJ6Service', true],
            'App\\Controller\\ConseilController:update' => ['privates', '.service_locator.YSLHiAd', 'get_ServiceLocator_YSLHiAdService', true],
            'App\\Controller\\DemandeController:add' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\DemandeController:conseiller' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\DemandeController:delete' => ['privates', '.service_locator.jJfxXMU', 'get_ServiceLocator_JJfxXMUService', true],
            'App\\Controller\\DemandeController:index' => ['privates', '.service_locator.KKOSzu8', 'get_ServiceLocator_KKOSzu8Service', true],
            'App\\Controller\\DemandeController:indexAdmin' => ['privates', '.service_locator.KKOSzu8', 'get_ServiceLocator_KKOSzu8Service', true],
            'App\\Controller\\DemandeController:update' => ['privates', '.service_locator.jJfxXMU', 'get_ServiceLocator_JJfxXMUService', true],
            'App\\Controller\\LivraisonController:Add' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\LivraisonController:AfficheLivraison' => ['privates', '.service_locator.7EutsTK', 'get_ServiceLocator_7EutsTKService', true],
            'App\\Controller\\LivraisonController:AfficheLivraison1' => ['privates', '.service_locator.RPKG70Q', 'get_ServiceLocator_RPKG70QService', true],
            'App\\Controller\\LivraisonController:Delete' => ['privates', '.service_locator.kXoQeZ1', 'get_ServiceLocator_KXoQeZ1Service', true],
            'App\\Controller\\LivraisonController:update' => ['privates', '.service_locator.rdBZ6dk', 'get_ServiceLocator_RdBZ6dkService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\CommandeController::Add' => '?',
            'App\\Controller\\CommandeController::AfficheCommande' => '?',
            'App\\Controller\\CommandeController::AfficheCommandeAdmin' => '?',
            'App\\Controller\\CommandeController::Delete' => '?',
            'App\\Controller\\CommandeController::sendMessage' => '?',
            'App\\Controller\\CommandeController::update' => '?',
            'App\\Controller\\ConseilController::add' => '?',
            'App\\Controller\\ConseilController::delete' => '?',
            'App\\Controller\\ConseilController::index' => '?',
            'App\\Controller\\ConseilController::update' => '?',
            'App\\Controller\\DemandeController::add' => '?',
            'App\\Controller\\DemandeController::conseiller' => '?',
            'App\\Controller\\DemandeController::delete' => '?',
            'App\\Controller\\DemandeController::index' => '?',
            'App\\Controller\\DemandeController::indexAdmin' => '?',
            'App\\Controller\\DemandeController::update' => '?',
            'App\\Controller\\LivraisonController::Add' => '?',
            'App\\Controller\\LivraisonController::AfficheLivraison' => '?',
            'App\\Controller\\LivraisonController::AfficheLivraison1' => '?',
            'App\\Controller\\LivraisonController::Delete' => '?',
            'App\\Controller\\LivraisonController::update' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\CommandeController:Add' => '?',
            'App\\Controller\\CommandeController:AfficheCommande' => '?',
            'App\\Controller\\CommandeController:AfficheCommandeAdmin' => '?',
            'App\\Controller\\CommandeController:Delete' => '?',
            'App\\Controller\\CommandeController:sendMessage' => '?',
            'App\\Controller\\CommandeController:update' => '?',
            'App\\Controller\\ConseilController:add' => '?',
            'App\\Controller\\ConseilController:delete' => '?',
            'App\\Controller\\ConseilController:index' => '?',
            'App\\Controller\\ConseilController:update' => '?',
            'App\\Controller\\DemandeController:add' => '?',
            'App\\Controller\\DemandeController:conseiller' => '?',
            'App\\Controller\\DemandeController:delete' => '?',
            'App\\Controller\\DemandeController:index' => '?',
            'App\\Controller\\DemandeController:indexAdmin' => '?',
            'App\\Controller\\DemandeController:update' => '?',
            'App\\Controller\\LivraisonController:Add' => '?',
            'App\\Controller\\LivraisonController:AfficheLivraison' => '?',
            'App\\Controller\\LivraisonController:AfficheLivraison1' => '?',
            'App\\Controller\\LivraisonController:Delete' => '?',
            'App\\Controller\\LivraisonController:update' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
