<?php

namespace ContainerYp6jxb7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RPKG70QService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RPKG70Q' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RPKG70Q'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'commandeRepo' => ['privates', 'App\\Repository\\CommandeRepository', 'getCommandeRepositoryService', true],
            'livraisonRepo' => ['privates', 'App\\Repository\\LivraisonRepository', 'getLivraisonRepositoryService', true],
        ], [
            'commandeRepo' => 'App\\Repository\\CommandeRepository',
            'livraisonRepo' => 'App\\Repository\\LivraisonRepository',
        ]);
    }
}
