<?php

namespace ContainerYp6jxb7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KKOSzu8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KKOSzu8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KKOSzu8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
            'repository' => ['privates', 'App\\Repository\\DemandeRepository', 'getDemandeRepositoryService', true],
        ], [
            'paginator' => '?',
            'repository' => 'App\\Repository\\DemandeRepository',
        ]);
    }
}
