<?php

namespace ContainerYp6jxb7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2p4gJ6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2p4g_J6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2p4g_J6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repository' => ['privates', 'App\\Repository\\ConseilRepository', 'getConseilRepositoryService', true],
        ], [
            'repository' => 'App\\Repository\\ConseilRepository',
        ]);
    }
}
