<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBFK2USD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBFK2USD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBFK2USD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBFK2USD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBFK2USD\App_KernelDevDebugContainer([
    'container.build_hash' => 'BFK2USD',
    'container.build_id' => 'a9bd40ed',
    'container.build_time' => 1740680033,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBFK2USD');
