<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCYMmiOx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCYMmiOx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCYMmiOx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCYMmiOx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCYMmiOx\App_KernelDevDebugContainer([
    'container.build_hash' => 'CYMmiOx',
    'container.build_id' => '5ceea4b7',
    'container.build_time' => 1738917993,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCYMmiOx');
